#!/bin/sh

SUITES_FOLDER="src/tests/resources"

##############
# Utils
func_result=''
STATUS=''
WD_CLIENT='local'
THREADS=1
COUNTER=0
BGREEN='\033[1;32m' # Bold Green
NO_COLOR='\033[0m' # No Color
BOLD='\033[1m'

##############
# Run-command args
USAGE=$BGREEN"\nUsage:"$NO_COLOR" $(basename "$0")\n \
      $(basename "$0") [-r [-T threads] | [-T threads] | -h]\n \
      $(basename "$0") [-G start [-T threads]]\n \
      $(basename "$0") [-G stop]\n \
       \n  h : print this help message \
       \n  r : runs the test suite against a remote Chrome Selenium node\n \
       \n  g start          : use \`start\' to start a Selenium Node \
       \n  g start -T nodes : use \`nodes\' to specify the amount of Chrome Selenium nodes to create \
       \n  g stop           : use \`stop\' to stop the current Selenium Grid \
       \n  r -T threads     : use \`threads\' to specify the amount of Chrome Selenium nodes used to run the test suite in parallel  \
       \n  t threads        : use \`threads\' to specify the amount of threads used to run the test suite in parallel\n";

while getopts ":rhT:G:" flag
do
    case "${flag}" in
        r) WD_CLIENT="remote";;
        T) THREADS="${OPTARG}";;
        G) SG_ACTION="${OPTARG}";;
        h) printf "$USAGE" 1>&2 ; exit 1;;
        ?) printf $BOLD"$(basename "$0"): illegal option: -${OPTARG}\n$USAGE\n"$BOLD; exit 1 ;;
    esac
done

##############
# Containers
#
# The-Internet app
CONTAINER_APP_IMAGE="gprestes/the-internet";
CONTAINER_APP_PORTS="7080:5000";
CONTAINER_APP_RUN_CMD="docker run -d \
      --rm --net dotdash --name website \
      -p 7080:5000 $CONTAINER_APP_IMAGE";
#
# Selenium hub
CONTAINER_SELENIUM_HUB_IMAGE="selenium/hub:4.5.2-20221021";
CONTAINER_SELENIUM_HUB_PORTS="4442-4444:4442-4444";
CONTAINER_SELENIUM_HUB_RUN_CMD="docker run -d \
      -e SE_VNC_NO_PASSWORD=1 \
      --rm --net dotdash --name selenium-hub \
      -p 4442-4444:4442-4444 \
      -v /dev/shm:/dev/shm "$CONTAINER_SELENIUM_HUB_IMAGE;
#
# Chrome nodes
CONTAINER_CHROME_NODES_IMAGE="selenium/node-chrome:4.5.2-20221021";
CONTAINER_CHROME_NODES_RUN_CMD="docker run -d --name chrome-node%s \
      --net dotdash -e SE_EVENT_BUS_HOST=selenium-hub \
      -v ""$(pwd)""/target:/home/seluser/Downloads \
      --shm-size='2g' -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
      -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 "$CONTAINER_CHROME_NODES_IMAGE;


run_container() {
  CONTAINER_RUN_CMD=$1

  # Run container
  CID=$(eval "$CONTAINER_RUN_CMD") 1>&2
  if [ ! "$CID" ]; then
    echo "Container doesn't exist";
  else
    printf "\r\033[K[OK] $STATUS | Id: $CID\n";
  fi
  unset CID
}

docker_container_startup () {
  CONTAINER_IMAGE=$1
  CONTAINER_RUN_CMD=$2
  IFS=" "; CONTAINER_NAME=$(echo $CONTAINER_RUN_CMD | grep -o -E "\-\-name[[:blank:]].+[[:blank:]]" | cut -w -f 2);
  STATUS="Container image: "$CONTAINER_IMAGE" | name: "$CONTAINER_NAME"";
  printf "$STATUS";

  # Container cleanup
  match=$(echo $CONTAINER_RUN_CMD | grep $CONTAINER_NAME | wc -l);
  if [ "$match" -gt 0 ]; then
    docker rm -f "$CONTAINER_NAME" > /dev/null 2>&1
  fi

  # Clear other statuses as well
  var=$(docker ps -aq -f status=exited -f ancestor="$CONTAINER_IMAGE" | xargs docker rm -f > /dev/null 2>&1)
  var=$(docker ps -aq -f status=paused -f ancestor="$CONTAINER_IMAGE" | xargs docker rm -f > /dev/null 2>&1)
  var=$(docker ps -aq -f status=dead -f ancestor="$CONTAINER_IMAGE" | xargs docker rm -f > /dev/null 2>&1)

  # Run the container
  run_container "$CONTAINER_RUN_CMD"
  STATUS=''
}

wait_until_container_is_ready() {
  # Get server port
  SERVER=$1;
  IFS=":"; read -a starr <<< "$2";
  PORTS=${starr[0]};

  if [[ $PORTS =~ "-" ]]; then
    IFS="-"; read -a starr2 <<< "$PORTS"; PORT=${starr2[1]}
  else
    PORT=${PORTS[0]}
  fi

  # Wait until the server is online
  printf "Trying $SERVER:$PORT ";
  until STATUS=$(nc -z "$SERVER" "$PORT" > /dev/null 2>&1); do
    printf ".";
    sleep 1;
  done;
  printf "\r\033[K[OK] Connection to $SERVER port $PORT succeeded!"
  STATUS=''
}

start_chrome_nodes() {
COUNTER=$1
  while [[ $COUNTER -ne 0 ]]
  do
    docker_container_startup "$CONTAINER_CHROME_NODES_IMAGE" "$(printf "$CONTAINER_CHROME_NODES_RUN_CMD" "$COUNTER")"
    COUNTER=$((COUNTER-1));
  done
}

missing_the_internet_app() {
  var=$(docker images | grep "gprestes/the-internet" | grep "latest" | wc -l)
  printf "The-internet App image \r"
  if [ ! "$var" ]; then
    func_result="docker pull gprestes/the-internet:latest";
  else
    func_result=""
  fi
}

missing_selenium_grid() {
  var=$(docker images | grep "selenium/hub" | grep "latest" | wc -l)
  printf "Selenium grid image \r"
  if [ ! "$var" ]; then
    func_result="docker pull selenium/hub:latest";
  else
    func_result=""
  fi
}

missing_chrome_nodes() {
  var=$(docker images | grep "selenium/node-chrome" | grep "4.5.2-20221021" | wc -l)
  printf "Chrome node image \r"
  if [ ! "$var" ]; then
    func_result="docker pull selenium/node-chrome:4.5.2-20221021";
  else
    func_result=""
  fi
}

missing_docker_network_config() {
  var=$(docker network inspect dotdash | grep "dotdash" | wc -l)
  printf "Bridge network configuration \r"
  if [ ! "$var" ]; then
    func_result="docker network create -o com.docker.network.bridge.bridge dotdash";
  else
    func_result=""
  fi
}

##############
# Setup
setup_where_necessary() {
printf "\n[""$BGREEN""Checking dependencies""$NO_COLOR""]\n";
missing_docker_network_config
if [ ! "$(eval "$func_result")" ]; then printf "[OK] Bridge network configuration\n"; fi
missing_the_internet_app
if [ ! "$(eval "$func_result")" ]; then printf "[OK] The-internet App image\n"; fi
missing_selenium_grid
if [ ! "$(eval "$func_result")" ]; then printf "[OK] Selenium grid image\n"; fi
missing_chrome_nodes
if [ ! "$(eval "$func_result")" ]; then printf "[OK] Chrome node image\n"; fi #&
#wait

chmod +x restart-grid.sh > /dev/null 2>&1
}

##############
# Clean, build, install, and run the test suite
execute_the_tests() {

  printf "$BGREEN""\n[Clean]\n""$NO_COLOR"
  mvn clean -f pom.xml
  printf "$BGREEN""\n[Compile]\n""$NO_COLOR"
  mvn compile -f pom.xml
  printf "$BGREEN""\n[Install]\n""$NO_COLOR";
  mvn install -f pom.xml -DskipTests
  wait
  printf "$BGREEN""\n[Running the test suite]\n""$NO_COLOR"
  # Local run
  if [[ "${WD_CLIENT}" == "remote" ]]; then
    mvn test -e -DsuiteXmlFile="$SUITES_FOLDER"/regression.xml;
  elif [[ "${WD_CLIENT}" == "local" ]]; then
  # Selenium grid run
    mvn test -e -DsuiteXmlFile="$SUITES_FOLDER"/regression-selenium-grid.xml;
  fi;
}

stop_containers() {
  NAMES=$1;
  echo "\n[Stopping containers]";
  if [ "$NAMES" ]; then
    if [[ $NAMES =~ "," ]]; then
      IFS=","; read -a starr <<< "$NAMES";
      for i in "${starr[@]}"
      do
        echo $i;
        docker ps -a -q --filter "name=""$i" | xargs docker rm -f
      done
    else
      docker rm -f "$(docker ps -a -q --filter ancestor=gprestes/the-internet)";
    fi;
  else
    if [ "$WD_CLIENT" = "remote" ]; then
    docker rm -f "$(docker ps -a -q --filter ancestor=selenium/hub:4.5.2-20221021)";
    docker rm -f "$(docker ps -a -q --filter ancestor=selenium/node-chrome:4.5.2-20221021 --format="{{.ID}}")";
    fi;
  fi;
}

##############
# Starting everything
main() {
  setup_where_necessary;

  # On Selenium grid action [start | stop]
  if [ "$SG_ACTION" ]; then
    USAGE="Usage: $(basename "$0") -g [start | stop]";
    case $SG_ACTION in
      start)
        # The-internet
        printf "\n[""$BGREEN""Starting The-Internet App""$NO_COLOR""]\n";
        docker_container_startup "$CONTAINER_APP_IMAGE" "$CONTAINER_APP_RUN_CMD";
        wait_until_container_is_ready "0.0.0.0" "$CONTAINER_APP_PORTS";
        # Selenium grid
        printf "\n[""$BGREEN""Starting Selenium Grid""$NO_COLOR""]\n";
        docker_container_startup "$CONTAINER_SELENIUM_HUB_IMAGE" "$CONTAINER_SELENIUM_HUB_RUN_CMD";
        wait_until_container_is_ready "0.0.0.0" "$CONTAINER_SELENIUM_HUB_PORTS";
        # Chrome nodes
        printf "\n[""$BGREEN""Starting Chrome nodes""$NO_COLOR""]\n";
        start_chrome_nodes "$THREADS";
        exit 0;;
      stop)
        stop_containers "website,selenium-hub,chrome-node"; exit 0;;
      *)
        echo "$USAGE" 1>&2 ; exit 1;;
    esac
  # On standard call via -t and -d args
  else
    # Init The-Internet App
    printf "\n[""$BGREEN""Starting The-Internet App""$NO_COLOR""]\n";
    docker_container_startup "$CONTAINER_APP_IMAGE" "$CONTAINER_APP_RUN_CMD";
    wait_until_container_is_ready "0.0.0.0" "$CONTAINER_APP_PORTS";

    # Init Selenium Grid and Chrome nodes
    if [[ "$WD_CLIENT" == "remote" ]]; then
      printf "\n[""$BGREEN""Starting Selenium Grid""$NO_COLOR""]\n";
      docker_container_startup "$CONTAINER_SELENIUM_HUB_IMAGE" "$CONTAINER_SELENIUM_HUB_RUN_CMD";
      wait_until_container_is_ready "0.0.0.0" "$CONTAINER_SELENIUM_HUB_PORTS";
      printf "\n[""$BGREEN""Starting Chrome nodes""$NO_COLOR""]\n";
      start_chrome_nodes "$THREADS";
    fi;

    # Run the test suite
    execute_the_tests;

    # Link to test report
    printf '\n\n['"${BGREEN}"'Test results report: \e]8;;file://%s/target/surefire-reports/index.html\e\\Link to test report\e]8;;\e\\]\n'"${NO_COLOR}"'' "$(pwd)";

    #stop_containers;
    stop_containers "website,selenium-hub,chrome-node"
  fi;
}

main;