public class UrlConstants {
    public static final String Login_URL =  "http:\\localhost:7080\\login";
    public static final String UsernameId = "username";
    public static final String User_Name = "tomsmith";
    public static final String Wrong_User_Name = "sowmyamacha";
    public static final String PasswordId = "password";
    public static final String Password = "SuperSecretPassword!";
    public static final String Wrong_Password = "!@WorstPass945782";
    public static final String Login_Button_Class = "radius";
    public static final String Checkbox_1_Text = "//*[@id=\"checkboxes\"]/input[1]";
    public static final String Checkbox_2_Text = " checkbox 2 ";
    public static final String Context_Menu_Id = "hot-spot";
    public static final String Drop_Down_Id = "dropdown";
    public static final String Drop_Down_Value_1 = "1";
    public static final String Drop_Down_Value_2 = "2";
    public static final String Drag_And_Drop_Id_A = "column-a";
    public static final String Drag_And_Drop_Id_B = "column-b";
    public static final String Download_File_Text = "some-file.txt";
    public static final String Upload_File_Text = "upload-some-file.txt";
    public static final String Upload_File_Id = "drag-drop-upload";
    public static final String CheckBoxes = "http:\\localhost:7080\\checkboxes";
    public static final String ContextMenu = "http:\\localhost:7080\\context_menu";
    public static final String Drag_and_Drop = "http:\\localhost:7080\\drag_and_drop";
    public static final String Dropdown = "http:\\localhost:7080\\dropdown";
    public static final String Dynamic_Content = "http:\\localhost:7080\\dynamic_content";
    public static final String Dynamic_Controls =  "http:\\localhost:7080\\dynamic_controls";
    public static final String Dynamic_Loading = "http:\\localhost:7080\\dynamic_loading\\2";
    public static final String File_Download = "http:\\localhost:7080\\download";
    public static final String File_Upload = "http:\\localhost:7080\\upload";
    public static final String Floating_Menu = "http:\\localhost:7080\\floating_menu";
    public static final String Iframe = "http:\\localhost:7080\\iframe";
    public static final String Mouse_Hover = "http:\\localhost:7080\\hovers";
    public static final String JavaScript_Alerts = "http:\\localhost:7080\\javascript_alerts";
    public static final String JavaScript_Error = "http:\\localhost:7080\\javascript_error";
    public static final String Open_in_New_Tab = "http:\\localhost:7080\\windows";
    public static final String Notification_Message = "http:\\localhost:7080\\notification_message_rendered";
}