# Workflow to run automated tests on code pushed to master branch

name: Run automated tests on code pushed to master
env:
  LOG_LEVEL: info
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: ${{ env.LOG_LEVEL }}
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    services:
      website:
        image: gprestes/the-internet:latest
        ports:
          - 7080:5000
        options: >-
          --rm
    steps:
    - name: Checkout repo code 
      uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'corretto'
    - name: Clean 
      run: mvn clean -f pom.xml --batch-mode --update-snapshots 
    - name: Build
      run: mvn compile -f pom.xml --batch-mode --update-snapshots
    - name: Install
      run: mvn install -f pom.xml -DskipTests --batch-mode --update-snapshots
    - name: Run the test suite
      run: mvn test -e -DsuiteXmlFile=regression.xml -DuseSeleniumGrid=false -DtestsThreadCount=4 --batch-mode --update-snapshots -Dorg.slf4j.simpleLogger.defaultLogLevel=${{ needs.workflow_dispatch.inputs.logLevel.default }}
    - uses: actions/upload-artifact@v2
      if: always()
