# Workflow to run automated tests on code pushed to master branch

name: Run automated tests suite
env:
  LOG_LEVEL: info
on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: info
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      chromeVersion:
        description: 'Chrome Version'
        required: true
        default: '106.0.5249.119'
        type: choice
        options:
          - "latest"
          - "106.0.5249.119"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    services:
      website:
        image: gprestes/the-internet:latest
        ports:
          - 7080:5000
        options: >-
          --rm
    steps:
    - name: Checkout repo code 
      uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'corretto'
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version && whoami
    - name: Clean 
      run: mvn clean -f pom.xml --batch-mode --update-snapshots 
    - name: Build
      run: mvn compile -f pom.xml --batch-mode --update-snapshots
    - name: Run the test suite
      run: >-
        mvn test -e 
        -DsuiteXmlFile=regression.xml -DheadlessBrowser=false
        -Dbrowser="remote-chrome"
        -DbrowserVersion=${{ needs.workflow_dispatch.inputs.chromeVersion.default }}
        -DtestRunnerAddress="http://0.0.0.0:7080" 
        -DwebAppAddress="http://0.0.0.0:7080"
        -DuseSeleniumGrid=false -DtestsThreadCount=4
        -DseleniumGridAddress="http://0.0.0.0:4444/wd/hub" 
        -Dorg.slf4j.simpleLogger.defaultLogLevel=${{ needs.workflow_dispatch.inputs.logLevel.default }}
        --batch-mode --update-snapshots
    - name: Install
      run: mvn install -f pom.xml -DskipTests --batch-mode --update-snapshots
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Test run report
        path: target/
    - name: Display structure of uploaded files
      run: ls -R
      working-directory: target/